languageCode = "de"
languageName = "Deutsch"
weight = 1
title = "geis.haus"

[params]
displayName = "DE"
isoCode = "de"
rtl = false
description = "geis.haus startseite"
dateFormat = "2 January 2006"
logo = ""

[params.author]
name = "Jakob Geishauser Hald"
image = "img/frontportrait.png"
headline = "Problem- und lösungsorientierter Designer."
bio = ""

[[params.author.links]]
email = "mailto:jakob.v.g.hald@gmail.com"
linkedin = "https://linkedin.com/in/jakob-geishauser-hald-11a2922b5"
