[[main]]
name = "Projekter"
pageRef = "/projects"
weight = 50

[[main]]
identifier = "linkedin"
pre = "linkedin"
url = "https://linkedin.com/in/jakob-geishauser-hald-11a2922b5"
weight = 10


[[footer]]
none = "none"
